_extends: jellyfin-meta-plugins

template: |
  <!-- Optional: add a release summary here -->
  [Plugin build can be downloaded here](https://github.com/jellyfin/jellyfin-plugin-trakt/releases/).

  ## :sparkles: What's New

  $CHANGES
